name: frontend
description: Simple todo management app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc:
    ^8.1.3
  http: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true